name: Build Addon

on:
  push:
    branches: [mac-build-test]
  pull_request:
    branches: [mac-build-test]

jobs:
  build:
    name: Build on ${{ matrix.os }} with Node.js ${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest] # [] #, windows-latest,
        node: [18, 20, 21, 24] # you can adjust Node.js versions

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install libmodbus
        run: |
          mkdir $GITHUB_WORKSPACE/deps
          if [[ "$RUNNER_OS" == "Linux" ]]; then
            sudo apt-get update -y
            sudo DEBIAN_FRONTEND=noninteractive apt-get install -y libmodbus-dev
            sudo cp $GITHUB_WORKSPACE/bin/libmodbus.a $GITHUB_WORKSPACE/deps/libmodbus.a

          elif [[ "$RUNNER_OS" == "macOS" ]]; then
            brew install automake libtool
            git clone https://github.com/stephane/libmodbus.git
            cd libmodbus && ./autogen.sh
            ./configure --disable-shared --enable-static
            make
            sudo cp src/.libs/libmodbus.a $GITHUB_WORKSPACE/deps/libmodbus.a

          fi

      - name: Install dependencies
        run: |
          pwd
          ls deps/
          npm install

      - name: Build addon
        run: npm run build  # Make sure this calls node-gyp correctly
